### ISSUE TITLE
Does not work with Nuke 0.16.0

### ISSUE THREAD

**Issue by jgilm** [GeorgDangl/Nuke.WebDeploy#1]
Looks like the `ToolSettings` class changed between this supported version and the latest (0.16.0) of Nuke.

An abstract property was added called `CustomLogger` that does not allow this package to work with the latest Nuke.

**Comment by GeorgDangl** [comment]
Hey Jim, thanks for raising this issue!
I'm currently blocked on updating this package until https://github.com/nuke-build/azure-keyvault/pull/2 is merged.

The build script in Nuke.WebDeploy relies on Nuke.Azure.KeyVault, so I can't go higher than 0.11.1. The code generator in 0.11.1, however, doesn't create the `CustomLogger` property.

@matkoch, any ETA when you could take a look at the PR in azure-keyvault?

**Comment by GeorgDangl** [comment]
Hey @jgilm and @alexshyba, it's been updated to NUKE 0.19.1 and should now work with the latest release:
https://github.com/GeorgDangl/Nuke.WebDeploy/releases/tag/v1.3.0

**Comment by jgilm** [comment]
Thanks a lot. I was just thinking about asking again.
