### ISSUE TITLE
Does not work with .NetCore build project

### ISSUE THREAD

**Issue by rajivchaudhary** [GeorgDangl/Nuke.WebDeploy#2]
Hi Georg,
After adding nuget package "Nuke.WebDeploy" to my Nuke build project. I get following error:

Package 'Nuke.WebDeploy 1.2.1' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.	_build

Do we have support for .NETCore project as well for "Nuke.WebDeploy"?

**Comment by GeorgDangl** [comment]
Hi @rajivchaudhary,

unfortunately, Nuke.WebDeploy depends on the [Microsoft.Web.Deployment](https://www.nuget.org/packages/Microsoft.Web.Deployment/) package, which only has a target for `net40`.
